### ISSUE TITLE
How can we find out which document is causing this

### ISSUE THREAD

**Issue by jcantrill** [openshift/origin-aggregated-logging#1491] opened 2019-01-02 21:22 UTC
How do we find out which document is causing this? I assume this is a mapping issue where the mapping is expecting one thing and maybe fluent is populating another?
```
[2019-01-02T21:19:36,896][DEBUG][o.e.a.b.TransportShardBulkAction] [logging-es-data-master-278firrc] [project.insights-qa.0f9e1ef6-f998-11e8-b728-12b1d165d92c.2019.01.02][0] failed to execute bulk item (create) BulkShardRequest [[project.insights-qa.0f9e1ef6-f998-11e8-b728-12b1d165d92c.2019.01.02][0]] containing [21] requests
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [args]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:298) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:468) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:591) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.mapper.DocumentParser.parseNonDynamicArray(DocumentParser.java:580) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.mapper.DocumentParser.parseArray(DocumentParser.java:526) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:385) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:373) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:93) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:66) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:277) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:530) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:507) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.prepareIndexOperationOnPrimary(TransportShardBulkAction.java:458) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:466) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:145) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:114) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:69) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:975) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:944) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:345) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:270) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:924) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:921) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:151) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1659) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:933) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:92) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:291) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:266) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:248) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceivedDecorate(SearchGuardSSLRequestHandler.java:178) [search-guard-ssl-5.6.10.23-redhat-1.jar:5.6.10.23-redhat-1]
	at com.floragunn.searchguard.transport.SearchGuardRequestHandler.messageReceivedDecorate(SearchGuardRequestHandler.java:107) [search-guard-5-5.6.10.19-2-redhat-1.jar:?]
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceived(SearchGuardSSLRequestHandler.java:92) [search-guard-ssl-5.6.10.23-redhat-1.jar:5.6.10.23-redhat-1]
	at com.floragunn.searchguard.SearchGuardPlugin$5$1.messageReceived(SearchGuardPlugin.java:493) [search-guard-5-5.6.10.19-2-redhat-1.jar:?]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:654) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:674) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NumberFormatException: For input string: "Connection to 172.30.97.113:5672 failed: [Errno 113] No route to host"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:?]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_191]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.longValue(AbstractXContentParser.java:187) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$7.parse(NumberFieldMapper.java:737) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$7.parse(NumberFieldMapper.java:709) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.mapper.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:1072) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:287) ~[elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1]
```

**Comment by richm** [comment] 2019-01-02 21:31
Is there a corresponding error in the fluentd log?  There should be.

**Comment by jcantrill** [comment] 2019-01-02 21:32
many of these:

```
2019-01-02 21:22:18 +0000 [warn]: dump an error event: error_class=Fluent::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch" location=nil tag="output_tag" time=1546464119 record={"relativeCreated"=>10130.167961120605, "process"=>1, "@timestamp"=>"2019-01-02T21:21:59.387778947Z", "args"=>["Connection to 172.30.97.113:5672 failed: [Errno 113] No route to host"], "component"=>"insights-plugins", "module"=>"blocking_connection", "funcName"=>"_flush_output", "message"=>"Connection open failed - 'Connection to 172.30.97.113:5672 failed: [Errno 113] No route to host'", "name"=>"pika.adapters.blocking_connection", "thread"=>140515297294144, "created"=>1546464119.387677, "threadName"=>"MainThread", "msecs"=>387.6769542694092, "filename"=>"blocking_connection.py", "levelno"=>40, "processName"=>"MainProcess", "source_host"=>"insights-plugins-amqp-1-rh2ff", "pathname"=>"/opt/app-root/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", "lineno"=>467, "@version"=>1, "levelname"=>"ERROR", "docker"=>{"container_id"=>"beb846d5dabd9d201a1a8938ec3cbd5e8b777740a6e6a768ff4d4a6f2b685416"}, "kubernetes"=>{"container_name"=>"insights-plugins", "namespace_name"=>"insights-qa", "pod_name"=>"insights-plugins-amqp-1-rh2ff", "pod_id"=>"4a11431f-03ba-11e9-aee7-1291bd654ec0", "labels"=>{"app"=>"insights-plugins-amqp", "deployment"=>"insights-plugins-amqp-1", "deploymentconfig"=>"insights-plugins-amqp"}, "host"=>"ip-172-28-62-69.ec2.internal", "master_url"=>"https://kubernetes.default.svc.cluster.local", "namespace_id"=>"0f9e1ef6-f998-11e8-b728-12b1d165d92c"}, "level"=>"info", "hostname"=>"ip-172-28-62-69.ec2.internal", "pipeline_metadata"=>{"collector"=>{"ipaddr4"=>"10.128.34.2", "ipaddr6"=>"fe80::d8ce:49ff:fe24:dc6d", "inputname"=>"fluent-plugin-systemd", "name"=>"fluentd", "received_at"=>"2019-01-02T21:22:18.238216+00:00", "version"=>"0.12.43 1.6.0"}}, "viaq_index_name"=>"project.insights-qa.0f9e1ef6-f998-11e8-b728-12b1d165d92c.2019.01.02", "viaq_msg_id"=>"ZGRkZjE0ZjItYmQ5OS00MWE2LWJjMzYtZjUwN2EyNzFkNmI4"}

```

**Comment by jcantrill** [comment] 2019-01-02 21:34
Is this a case of where maybe the content is merged into the JSON document and overwriting something we expect?

**Comment by jcantrill** [comment] 2019-01-02 21:40
From the prod cluster:  
```
java.lang.IllegalArgumentException: mapper [args] of different type, current_type [text], merged_type [long]
```
related?

**Comment by richm** [comment] 2019-01-02 21:42
> Is this a case of where maybe the content is merged into the JSON document and overwriting something we expect?

Yes. In this case, the content has a merged JSON field called `args` which is array valued: `"args"=>["Connection to 172.30.97.113:5672 failed: [Errno 113] No route to host"]` - Elasticsearch does not like that - https://github.com/ViaQ/elasticsearch-templates/blob/master/templates/skeleton.json#L50 - the default type for unknown fields is `string` - not sure if you can tell Elasticsearch to automatically convert unknown fields to strings, and store it as a JSON string.  @lukas-vlcek ?

**Comment by jcantrill** [comment] 2019-01-02 21:46
isnt this the issue we talked about where we "merge" fields to a subkey so to avoid this problem?

**Comment by richm** [comment] 2019-01-02 21:47
> isnt this the issue we talked about where we "merge" fields to a subkey so to avoid this problem?

I'm not sure if that will solve the problem, if we are sending over an `array` value but elasticsearch expects a `string` value.

**Comment by lukas-vlcek** [comment] 2019-01-03 09:40
Looking at the exception root cause:
```
Caused by: java.lang.NumberFormatException: For input string: "Connection to 172.30.97.113:5672 failed: [Errno 113] No route to host"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:?]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_191]
        ...
```
it seems ES already thought this content must have been convertible into `Double`; hence failing...
The fact that the value is inside an array is not a problem.

Is there a chance that some document that introduced the `args` field had value like `[200]` for it? **Are we sure that the value inside the array is always passed quoted?**

Here is a simple test I did:
```
$ curl -H 'Content-Type: application/json' -X PUT localhost:9200/my_index/my_type/1 -d '
{
  "num":[200],
  "text":["200"]
}'

{"_index":"my_index","_type":"my_type","_id":"1","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"created":true}

$ curl localhost:9200/_mappings?pretty
{
  "my_index" : {
    "mappings" : {
      "my_type" : {
        "properties" : {
          "num" : {
            "type" : "long"    ### <-- it is a number
          },
          "text" : {
            "type" : "text",   ### <-- it is a text
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
}}}}}}}}
```

Now, let's index another document with slightly modified `num` value:
```
$ curl -H 'Content-Type: application/json' -X PUT localhost:9200/my_index/my_type/2 -d '
{
  "num":["foo"],
  "text":["200"]
}'

{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [num]"}],"type":"mapper_parsing_exception","reason":"failed to parse [num]","caused_by":{"type":"number_format_exception","reason":"For input string: \"foo\""}},"status":400}
```
And the ES log reads:
```
[2019-01-03T10:34:27,879][DEBUG][o.e.a.b.TransportShardBulkAction] [c287aWJ] [my_index][2] failed to execute bulk item (index) BulkShardRequest [[my_index][2]] containing [index {[my_index][my_type][2], source[{"num":["foo"],"text":["200"]}]}]
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [num]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:298) ~[elasticsearch-5.6.14.jar:5.6.14]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:468) ~[elasticsearch-5.6.14.jar:5.6.14]
	[...]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NumberFormatException: For input string: "foo"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:543) ~[?:?]
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.longValue(AbstractXContentParser.java:187) ~[elasticsearch-5.6.14.jar:5.6.14]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$7.parse(NumberFieldMapper.java:737) ~[elasticsearch-5.6.14.jar:5.6.14]
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$7.parse(NumberFieldMapper.java:709) ~[elasticsearch-5.6.14.jar:5.6.14]
	at org.elasticsearch.index.mapper.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:1072) ~[elasticsearch-5.6.14.jar:5.6.14]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:287) ~[elasticsearch-5.6.14.jar:5.6.14]
	... 38 more
```
To me the exception looks exactly the same (except code line numbers for individual Java objects, may be due to different Java version?).

**Comment by lukas-vlcek** [comment] 2019-01-03 09:46
I think you have Java 1.8.0_191 and ES elasticsearch-5.6.10.redhat-1.jar:5.6.10.redhat-1
I have Java "11.0.1" 2018-10-16 LTS and ES elasticsearch-5.6.14.jar:5.6.14
So that could explain the slightly different source code line numbers in the exception trace.

**Comment by richm** [comment] 2019-01-03 18:09
I think the only way to handle this will be to add a custom `record_transformer` filter in fluent.conf which is run after the viaq filter plugin but before the retagging output filters.  This filter will convert the `args` field to its JSON string representation - something like this pseudo code:
```
<filter kubernetes.**> # should make this more specific if we can narrow the problem down to a specific namespace, pod, and/or container name
 \@type record_transformer
  enable_ruby true
  <record>
    args ${record['args'].to_json}
  </record>
</filter>
```

**Comment by richm** [comment] 2019-08-30 17:03
There are also a few new env. vars. to allow you to handle different cases when using `MERGE_JSON_LOG=true` - see https://github.com/openshift/origin-aggregated-logging/commit/f59ebef7e182d479d56cd1ea7c4958e2abeb8dc4#diff-a32833599445d5dea8691ecc8a286b3c

**Closed by richm** 2019-08-30 17:03 UTC
Labels: kind/bug
