### ISSUE TITLE
Document using supplementalGroups for NFS PV [for] backing ES

### ISSUE THREAD

**Issue by ewolinetz** [openshift/origin-aggregated-logging#178] opened 2016-06-22 16:08 UTC
This was discovered initially during CI testing of `MODE=reinstall` where when reinstalling a previously backed/populated ES cluster, the reinstalled cluster is unable to access the previous data

```
{1.5.2}: Initialization Failed ...
- ElasticsearchIllegalStateException[Failed to created node environment]
    AccessDeniedException[/elasticsearch/persistent/logging-es-ops/data/logging-es-ops/nodes/1]
```

**Comment by sosiouxme** [comment] 2016-06-22 20:35
We were thinking that this error was due to the running ES process UID/GID/MCS not matching up between invocations. But this now seems unlikely to be the cause.

If you don't specifically request user/group/selinux for a pod/container (and we don't), then the ranges for the SCC to choose from are specified by project annotations; so containers in the same project by default will always have the same security context and should have no trouble reusing each others' storage volumes. Something else must have been the issue for this error to come up, perhaps related to NFS settings.

It's still a good idea to enable users to set a supplemental group id for access to backing volumes, particularly NFS.

**Comment by jcantrill** [comment] 2019-02-13 22:22
closing without prejudice

**Closed by jcantrill** 2019-02-13 22:22 UTC
Labels: component/elasticsearch
