### ISSUE TITLE
Start requiring content-type for HTTP REST requests

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/origin-aggregated-logging#625] opened 2017-08-30 13:19 UTC
Elasticsearch accepts very convenient and _lenient_ syntax when using curl like this:

````
curl localhost:9200/_search -d '{ "query": { "match_all": {} }}'
````
Contrary to usual conventions it does not require specifying `content-type`. But this is changing in ES 6.x. While it may take us some time to upgrade to ES 6.x it is good to notice that it is already possible to start using `content-type` with ES 5.x. Although ES 5.x does not require `content-type` by default it is possible to configure it and make mandatory. There are also some (security) benefits if we start doing it. Read more at: <https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests>

//cc @t0ffel

**Comment by lzap** [comment] 2018-07-12 15:11
I guess this will need to be backported in RHEL7 anyway? Filed https://bugzilla.redhat.com/show_bug.cgi?id=1600171 in the meantime :-)

**Comment by richm** [comment] 2018-07-16 20:31
This primarily affects our test scripts that use `curl` and similar - the fluentd elasticsearch code has had support for content-type json for a long time.

**Comment by jonassteinberg1** [comment] 2018-11-02 19:14
Is there any update on this?  I'm very interested as it is affecting my team's fairly massive elasticsearch infrastructure.

**Comment by jonassteinberg1** [comment] 2018-11-02 19:42
I came here from (here)[https://bugzilla.redhat.com/show_bug.cgi?id=1600171].  I am curious if there is any update on either issue as this is affecting my elasticsearch 6 infrastructure.  I'd be happy to help in any way that I can.

**Comment by richm** [comment] 2018-11-02 21:16
@jonassteinberg1 I raised the severity of the rh bz to High.  Not sure what that will do. The problem is that rhel7 is now into 7.7, which means it gets more and more difficult to get patches in that are not for severe issues like crashing/CVEs.  The only way to get this fixed in rhel7 is to convince the rhel7 rsyslog maintainers to fix this for rhel7.7.  I'm hoping you are more persuasive than I.

**Comment by jonassteinberg1** [comment] 2018-11-02 22:52
@richm hm.  well...RHEL's rsyslog RPM doesn't work with elasticsearch lol, so...

**Comment by jcantrill** [comment] 2020-01-02 15:05
@lukas-vlcek is this relevent to our ES6 work?

**Comment by richm** [comment] 2020-01-04 00:04
> @lukas-vlcek is this relevent to our ES6 work?

Yes - see https://github.com/openshift/origin-aggregated-logging/pull/1801/files#diff-25a5922f0af6ad88a896bbda874af6ddR42

**Closed** 2020-11-24 15:06 UTC
Labels: lifecycle/rotten
