### ISSUE TITLE
Kibana authorisation errors, EFK stack in Openshift v3.3 (using Active Directory LDAP)

### ISSUE THREAD

**Issue by paulwinning** [openshift/origin-aggregated-logging#286] opened 2016-11-18 14:12 UTC
Hi,

New member, so apologies if providing too much detail or not enough.

Have ran a basic EFK deployment into our OpenShift v3.3 cluster (lab) with Active Directory integration and am seeing an authorisation error.  My AD account used for testing is a member of cluster admins.

After hitting the **URL** and entering credentials, I see:

https://<a server>.logging.dev.paas.<a domain>/auth/openshift/callback?error=access_denied&error_...

Unauthorized

**Error messages in the Kibana-proxy container:**

10.1.2.1 - - [16/Nov/2016:17:28:35 +0000] "GET /auth/openshift/callback?error=access_denied&error_description=scope+denied%3A+user%3Afull HTTP/1.1" 401 - 

Had a look at the **elasticsearch.yml** file on the ES containers:

SEARCHGUARD CONFIG

searchguard:                                                                                                                                                           
  config_index_name: ".searchguard.${HOSTNAME}"                                                                                                                        
  key_path: /elasticsearch/${CLUSTER_NAME}                                                                                                                             
  allow_all_from_loopback: false                                                                                                                                       
  authentication:                                                                                                                                                      
    authentication_backend:                                                                                                                                            
      impl: com.floragunn.searchguard.authentication.backend.simple.AlwaysSucceedAuthenticationBackend                                                                 
    authorizer:                                                                                                                                                        
      impl: com.floragunn.searchguard.authorization.simple.SettingsBasedAuthorizator                                                                                   
    http_authenticator:                                                                                                                                                
      impl: io.fabric8.elasticsearch.plugin.HTTPSProxyClientCertAuthenticator                                                                                          
    proxy:                                                                                                                                                             
      header: X-Proxy-Remote-User                                                                                                                                      
      trusted_ips: ["*"]                                                                                                                                               
    authorization:                                                                                                                                                     
      settingsdb:                                                                                                                                                      
        roles:                                                                                                                                                         
          admin: ["admin"]                                                                                                                                             
          fluentd: ["fluentd"]                                                                                                                                         
          kibana: ["kibana"]                                                                                                                                           
          curator: ["curator"]       

OPENSHIFT

openshift:                                                                                                                                                             
  acl:                                                                                                                                                                 
    users:                                                                                                                                                             
      names: ["system.logging.fluentd", "system.logging.kibana", "system.logging.curator", "system.admin"]                                                             
      system.logging.fluentd:                                                                                                                                          
        execute: ["actionrequestfilter.fluentd"]                                                                                                                       
        actionrequestfilter.fluentd.comment: "Fluentd can only write"                                                                                                  
      system.logging.kibana:                                                                                                                                           
        bypass: ["*"]                                                                                                                                                  
        execute: ["actionrequestfilter.kibana"]                                                                                                                        
        actionrequestfilter.kibana.comment: "Kibana can only read from every other index"                                                                              
      system.logging.kibana.*.comment: "Kibana can do anything in the kibana index"                                                                                    
      system.logging.kibana.*.indices: [".kibana.*"]                                                                                                                   
      system.logging.curator:                                                                                                                                          
        execute: ["actionrequestfilter.curator"]                                                                                                                       
        actionrequestfilter.curator.comment: "Curator can list all indices and delete them"                                                                            
      system.admin:                                                                                                                                                    
        bypass: ["*"]                                                                                                                                                  
      system.admin.*.comment: "Admin user can do anything" 

I can’t find any specific documentation that explains the overlap between SearchGuard and OPenShift configuration in ElasticSearch, but I certainly don’t see anything that maps my AD user/cluster-admin role for authorisation.

Would appreciate it if someone could point me in the right direction please ?

**Comment by jcantrill** [comment] 2016-11-18 15:44
Policy for specific users is given via openshift.  If you need a cluster-admin role  you can grant it to a user like:
```
oadm policy add-cluster-role-to-user cluster-admin <username>
```
ref: https://docs.openshift.com/enterprise/3.1/admin_guide/manage_authorization_policy.html

**Comment by paulwinning** [comment] 2016-11-18 15:54
Hi, thanks for replying.  The account I am using is already a cluster-admin in OpenShift.  As I say, don't see how the Openshift ACL section in the elasticsearch.yml file can map out to any AD account.  Appears to cater just for built in OC accounts - names: ["system.logging.fluentd", "system.logging.kibana", "system.logging.curator", "system.admin"]

**Comment by jcantrill** [comment] 2016-11-18 16:50
User access is dynamically updated in the ACL document used to restrict index access.  These accounts are reflective of service accounts and not how a user is granted access.  Their is a plugin that will dynamically change the ACL document based on the projects you are able to see as a user.

**Comment by paulwinning** [comment] 2016-11-22 13:45
The account I am logging onto OC with, has full access to all projects as cluster admin.  I suspect  adding the Active Directory LDAP integration into OC has broken the Kibana authorisation.  I'm not in a position to prove this by switching off AD integration and reverting to native OC accounts due to other people are using the cluster.  I have raised an issue with Red Hat and will post back any resolution.

**Comment by jcantrill** [comment] 2016-11-22 14:36
The kibana auth proxy uses the same OAUTH2 authentication that is used by the origin server.  If you are able to use OC as a cluster-admin you should also be able to use kibana without changes as both simply present your token when accessing resources.  @sosiouxme any thoughts here?

**Comment by sosiouxme** [comment] 2016-11-22 16:32
There happens to be a little more information in the proxy log:

    error_description=scope+denied%3A+user%3Afull

This indicates that the problem is with the scope request for the token rather than a failure to login. I suspect that either the image versions aren't the latest for 3.3 or that maybe policy was not updated in an upgrade to 3.3 (check on master with `oadm diagnostics`).

**Comment by paulwinning** [comment] 2016-11-24 10:22
Hi, Just to say I've had an update from RedHat to say that I cannot access the Kibana URL directly, but need to drill down into the appropriate POD in OpenShift, select logs, then view archive.  I can successfully view ES logs from there.

Still don't fully understand the underlying decisioning that's done by the OpenShift OATH server in relation to accessing specific indexes.  Maybe it's just as simple as having access to click the link within a POD in specific project, means that a token is produced that allows access to the associated index for that project.

**Comment by jcantrill** [comment] 2016-11-28 14:22
@paulwinning I'm not sure what you are asking here:

> Still don't fully understand the underlying decisioning that's done by the OpenShift OATH server in relation to accessing specific indexes. Maybe it's just as simple as having access to click the link within a POD in specific project, means that a token is produced that allows access to the associated index for that project.

Users are restricted in order to meet the multi-tenancy requirements of the platform.  The OpenShift EFK stack restricts index visibility to a user based upon the projects a user is allowed to see in OpenShift.  The EFK index pattern is structured to include the project name and UUID.

**Comment by jcantrill** [comment] 2016-11-29 14:18
@paulwinning Closing for now.  Please reopen if you feel it is appropriate.

**Closed by jcantrill** 2016-11-29 14:18 UTC

**Comment by stobias123** [comment] 2017-02-25 01:16
I'm seeing this exact issue, I'm not sure I understand the fix... Any help would be appreciated. I'm using my cluster-admin account when attempting to log into kibana and seeing "Unauthorized" in browser and seeing the following in the `kibana-proxy` container

`10.1.0.1 - - [25/Feb/2017:00:42:33 +0000] "GET /auth/openshift/callback?error=access_denied&error_description=scope+denied%3A+user%3Afull HTTP/1.1" 401 - "https://openshift.domain.com:8443/login?`

**Comment by richm** [comment] 2017-02-25 01:57
If you go directly to `https://openshift.domain.com:8443` in the browser, are you able to login?  If not, then this is not a Kibana or proxy issue.

**Comment by stobias123** [comment] 2017-02-25 02:11
Yes I am able to log into openshift without issue

**Comment by richm** [comment] 2017-02-25 02:17
@stobias123 What version of openshift are you using?  Can you attach your elasticsearch pod logs, and the kibana pod logs from both the kibana and the kibana-proxy containers?

**Comment by stobias123** [comment] 2017-03-07 21:13
Version
OpenShift Master:
v1.3.0
Kubernetes Master:
v1.3.0+52492b4

## kibana-proxy logs show 
```
10.1.0.1 - - [07/Mar/2017:21:10:47 +0000] "GET /favicon.ico HTTP/1.1" 302 0 "https://kibana.cloud.example.com/auth/openshift/callback?error=access_denied&error_description=scope+denied%3A+user%3Afull" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
10.1.0.1 - - [07/Mar/2017:21:10:48 +0000] "GET /auth/openshift/callback?error=access_denied&error_description=scope+denied%3A+user%3Afull HTTP/1.1" 401 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
10.1.0.1 - - [07/Mar/2017:21:10:48 +0000] "GET /favicon.ico HTTP/1.1" 302 0 "https://kibana.cloud.example.com/auth/openshift/callback?error=access_denied&error_description=scope+denied%3A+user%3Afull" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
```

## Kibana Container
```
{"type":"log","@timestamp":"2017-03-04T03:36:30Z","tags":["status","plugin:elasticsearch@1.0.0","info"],"pid":1,"state":"green","message":"Status changed from red to green - Kibana index ready","prevState":"red","prevMsg":"Request Timeout after 3000ms"}
{"type":"log","@timestamp":"2017-03-04T03:40:35Z","tags":["status","plugin:elasticsearch@1.0.0","error"],"pid":1,"state":"red","message":"Status changed from green to red - Request Timeout after 3000ms","prevState":"green","prevMsg":"Kibana index ready"}
{"type":"log","@timestamp":"2017-03-04T03:40:37Z","tags":["status","plugin:elasticsearch@1.0.0","info"],"pid":1,"state":"green","message":"Status changed from red to green - Kibana index ready","prevState":"red","prevMsg":"Request Timeout after 3000ms"}
{"type":"log","@timestamp":"2017-03-07T02:04:16Z","tags":["status","plugin:elasticsearch@1.0.0","error"],"pid":1,"state":"red","message":"Status changed from green to red - Request Timeout after 3000ms","prevState":"green","prevMsg":"Kibana index ready"}
{"type":"log","@timestamp":"2017-03-07T02:04:19Z","tags":["status","plugin:elasticsearch@1.0.0","info"],"pid":1,"state":"green","message":"Status changed from red to green - Kibana index ready","prevState":"red","prevMsg":"Request Timeout after 3000ms"}```

**Comment by richm** [comment] 2017-03-07 21:19
@stobias123 if you login to the openshift console, are you able to view the logs in any pod of which you are a member of the namespace/project?  If you use the `oc login ` from the command line, are you able to use `oc logs` to view logs of which you are a member of the namespace/project

**Comment by stobias123** [comment] 2017-03-07 21:21
Yes. Logging works fine anywhere else. I can log into web interface and see logs, I can view logs from `oc` tools. I'm cluster admin.

**Comment by richm** [comment] 2017-03-08 21:52
Can you try accessing elasticsearch directly from the cli using username/password/token auth?  Something like this: https://github.com/openshift/origin-aggregated-logging/blob/master/deployer/scripts/util.sh#L375 and https://github.com/openshift/origin-aggregated-logging/blob/master/deployer/scripts/util.sh#L391

    oc login --username=kibtest --password=kibtest > /dev/null
    test_token="$(oc whoami -t)"
    test_name="$(oc whoami)"
    test_ip="127.0.0.1"
    oc login --username=system:admin > /dev/null
    oc exec $kibana_pod -c kibana -- curl -s -k \
       --cert /etc/kibana/keys/cert --key /etc/kibana/keys/key \
       -H "X-Proxy-Remote-User: $test_name" -H "Authorization: Bearer $test_token" -H "X-Forwarded-For: 127.0.0.1" \
      https://logging-es:9200/

and see if that works.

**Comment by chasmosis** [comment] 2017-03-15 17:07
I am running into this exact issue as well, also I'm a cluster admin user.  The mail openshift UI works as fine as expected.

I ran thru the last item above and get good results back:
$ oc exec $kibana_pod -c kibana -- curl -s -k    --cert /etc/kibana/keys/cert --key /etc/kibana/keys/key    -H "X-Proxy-Remote-User: $test_name" -H "Authorization: Bearer $test_token" -H "X-Forwarded-For: 127.0.0.1"   https://logging-es:9200/
{
  "name" : "Base",
  "cluster_name" : "logging-es",
  "cluster_uuid" : "hIwvo91oQxigjskDKONwGA",
  "version" : {
    "number" : "2.4.4",
    "build_hash" : "fcbb46dfd45562a9cf00c604b30849a6dec6b017",
    "build_timestamp" : "2017-01-03T11:33:16Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}

This has my team and myself stumped at this point...

**Comment by richm** [comment] 2017-03-15 17:10
Are there any errors in the elasticsearch pod log?

**Comment by jcantrill** [comment] 2017-03-15 17:16
Can you also update the debug parameter for the proxy container: https://github.com/openshift/origin-aggregated-logging/blob/master/deployer/templates/kibana.yaml#L109  It might provide additional info

**Comment by stobias123** [comment] 2017-03-15 17:18
Sorry for the delayed response on this, I got the same result with the curl command. 

Looking at logs I saw the following warning. Could this be part of the problem? It's got several of these 
`[WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] project.mattermost.8403bf0e-94ae-11e6-ae6a-0050568b4a96.2017.03.15 does not exist in cluster metadata`

**Comment by jcantrill** [comment] 2017-03-15 17:20
@stobias123 I do not believe this is related.  This is an innocuous warning from our ES auth plugin about a missing index in the auth metadata.  You are stating you are not able to login to Kibana which, if you are a cluster admin, you should be into the kibana UI.  Are you able to log in as a regular user?

**Comment by stobias123** [comment] 2017-03-15 17:35
@jcantrill correct, regular users and cluster admin are both unable to login.

**Comment by chasmosis** [comment] 2017-03-15 19:01
Setting debug gets more in the kibana-proxy container logs but not a ton:

10.238.2.1 - - [15/Mar/2017:18:37:54 +0000] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
in callback handler for req path /auth/openshift/callback
10.238.2.1 - - [15/Mar/2017:18:38:04 +0000] "GET /auth/openshift/callback?error=access_denied&error_description=scope+denied%3A+user%3Afull HTTP/1.1" 401 - "https://master.originlab.ugcloud.local/login?then=%2Foauth%2Fauthorize%3Fresponse_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fkibana.originlab.ugcloud.local%252Fauth%252Fopenshift%252Fcallback%26client_id%3Dkibana-proxy" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
in passport.ensureAuthenticated for req path /favicon.ico
not authenticated by request session.
10.238.2.1 - - [15/Mar/2017:18:38:04 +0000] "GET /favicon.ico HTTP/1.1" 302 0 "https://kibana.originlab.ugcloud.local/auth/openshift/callback?error=access_denied&error_description=scope+denied%3A+user%3Afull" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

10.238.2.1 is one of our router pods.

**Comment by jcantrill** [comment] 2017-03-15 19:32
Depending on if this is 1.4 or not, consider running 'oadm diagnostics AggregatedLogging' from the master node.  
Also, could your oauth secrets not match?  The secret defined in oauthclient/kibana-proxy must match the secret/logging-kibana-proxy entry oauth-secret.

```
oc get oauthclient kibana-proxy -o jsonpath={.secret}
oc extract secret/logging-kibana-proxy --keys=oauth-secret --confirm & cat oauth-secret
```

**Comment by stobias123** [comment] 2017-03-15 23:06
Secrets match. 

I'm on 1.3 - diagnostics command returned an error "None of the requested diagnostics are available"

**Comment by chasmosis** [comment] 2017-03-15 23:21
same here, my secrets match and on 1.3

**Comment by chasmosis** [comment] 2017-03-16 20:03
We got past our kibana unauthorized error.  I had one of the guys who finally got past it write it up to post.  not sure if it will help anybody else but here it is:

Running through different options to try to resolve I believe had caused some of the persisting issues. Several uninstalls, I followed the logging guide, running the uninstall parameter but also running this command:
                oc delete all,sa,oauthclient --selector logging-infra

I tried several times to run just this command, but didn’t have luck. Possibly because along with the uninstall below I deleted all the other resources above.
*  oc new-app logging-deployer-template --param KIBANA_HOSTNAME=kibana.originlab.ugcloud.local --param ES_CLUSTER_SIZE=1 --param PUBLIC_MASTER_URL=https://master.originlab.ugcloud.local

The success this time I ran this command

- oc new-app logging-deployer-template --param MODE=uninstall
- then removed our hostmount /elastic contents.  NOTE: We are running a host mount for elasticsearch rather than a pvc
- Then reran our install with openshift_hosted_logging_deployer=true

Once completed I tested access to our KIBANA_HOSTNAME and could login.

On side note,  we also had an issue with metrics on origin install 1.3.3 , in that it fails to put the policy on the service account .Unrelated to logging, but have to have it working so have to run this.
•	oadm policy add-role-to-user edit  system:serviceaccount:openshift-infra:metrics-deployer  -n openshift-infra

**Comment by stobias123** [comment] 2017-03-16 23:00
@chasmosis what is this parameter? **openshift_hosted_logging_deployer=true** I can't find it mentioned in the docs anywhere

**Comment by chasmosis** [comment] 2017-03-20 19:02
Sorry thats a typo should be openshift_hosted_logging_deploy not openshift_hosted_logging_deployer

we're passing "openshfit_hosted_logging_deploy=true" when we fire the playbook to override our usual playbooks which have it set to false like the following
sudo ansible-playbook -i hosts.origin.lab -e openshift_hosted_logging_deploy=true -e deployment_type=origin config.yml
(cause on subsequent re-runs of the playbook it caused us issues when set to true when it was already working)

**Comment by tpolekhin** [comment] 2017-03-20 21:11
Hello, 

i'm having the same issue with `Unathourized` in Kibana, after reinstalling cluster from 1.3.1 to 1.4.1 version. Im using GitHub and htpasswd authentication mechanisms, and both accounts are `cluster-admins` role bind. I never experienced something like this in OS 1.3.1

I tried to do `oc new-app logging-deployer-template --param IMAGE_VERSION=v1.3.1`
and this issue is not present.

Only when i use `IMAGE_VERSION=v1.4.1` i get `Unathorized` in Kibana.

Any help appreciated

**Comment by dosmachko** [comment] 2017-03-24 12:00
@tpolekhin I had same issue that you have even same version on OpenShift cluster.

I To fix it just specify image_version parameter in template when deploying EFK. This can explain why  @chasmosis  was able to fix it via ansible installation, because when ansible bootstrapping openshift it deploys all components with same version as OpenShift.


P.S today I had issue with metrics also, because latest hawcular image is [broken](https://issues.jboss.org/browse/HWKMETRICS-632?_sscc=t). Redeploy metrics component also fixed this error.

**Comment by tpolekhin** [comment] 2017-03-28 12:42
@dosmachko i guess that's exactly what i did, and what i wrote above.
I tried `IMAGE_VERSION=v1.4.1` and got `Unauthorised` in Kibana.
I tried `IMAGE_VERSION=v1.3.1` and got it working.

**Comment by deanpeterson** [comment] 2017-04-27 04:35
I am getting the exact same error too and I am on Origin version 1.4.1. So the only solution is to force an old version of the kibana image?

**Comment by dosmachko** [comment] 2017-04-27 04:39
@deanpeterson, yes just use valid image version for kibana installation. Your Openshift is 1.4.1 so use same for kibana.

**Comment by deanpeterson** [comment] 2017-04-27 04:46
when i add IMAGE_VERSION=v1.4.1 the deployer does not work and displays: "image pull back off"

**Comment by dosmachko** [comment] 2017-04-27 04:47
@deanpeterson try using value 1.4.1 instead of V1.4.1

**Comment by deanpeterson** [comment] 2017-04-27 04:53
I left the v off by accident. Sorry. It looks like the deployment is working with v1.4.1. Thanks @dosmachko!

**Comment by donnydavis** [comment] 2017-05-12 00:13
Same here on 1.5.0, I had to specify the verison, which is mentioned in the install docs for older versions of origin. Fix seems to be working great so far. Thanks
