### ISSUE TITLE
Curator Test Broken

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/origin-aggregated-logging#444] opened 2017-05-30 15:05 UTC
Curator run failed to delete the hard-coded jobs, _e.g._:

```yml
project-dev:
  delete:
    days: 1
project-qe:
  delete:
    days: 7
project-prod:
  delete:
    weeks: 4
.operations:
  delete:
    months: 2
project2-qe:
  delete:
    days: 7
project3-qe:
  delete:
    days: 7
```

The indices were just not found: 

```
curator running [5] jobs
No indices matched provided args: {'regex': None, 'index': (), 'suffix': None, 'newer_than': None, 'closed_only': False, 'prefix': None, 'time_unit': 'days', 'timestring': u'%Y.%m.%d', 'exclude': (u'.searchguard*', u'.kibana*', u'project\\-qe\\.*', u'project2\\-qe\\.*', u'\\.operations\\.*', u'project3\\-qe\\.*', u'project\\-prod\\.*', u'project\\-dev\\.*'), 'older_than': 31, 'all_indices': False}
No indices matched provided args: {'regex': u'(^\\.operations\\.)', 'index': (), 'suffix': None, 'newer_than': None, 'closed_only': False, 'prefix': None, 'time_unit': 'months', 'timestring': u'%Y.%m.%d', 'exclude': (), 'older_than': 2, 'all_indices': False}
No indices matched provided args: {'regex': u'(^project\\.project\\-dev\\.)', 'index': (), 'suffix': None, 'newer_than': None, 'closed_only': False, 'prefix': None, 'time_unit': 'days', 'timestring': u'%Y.%m.%d', 'exclude': (), 'older_than': 1, 'all_indices': False}
No indices matched provided args: {'regex': u'(^project\\.project\\-prod\\.)', 'index': (), 'suffix': None, 'newer_than': None, 'closed_only': False, 'prefix': None, 'time_unit': 'days', 'timestring': u'%Y.%m.%d', 'exclude': (), 'older_than': 28, 'all_indices': False}
No indices matched provided args: {'regex': u'(^project\\.project\\-qe\\.|^project\\.project2\\-qe\\.|^project\\.project3\\-qe\\.)', 'index': (), 'suffix': None, 'newer_than': None, 'closed_only': False, 'prefix': None, 'time_unit': 'days', 'timestring': u'%Y.%m.%d', 'exclude': (), 'older_than': 7, 'all_indices': False}
curator run finish
```

As seen in [this job](https://ci.openshift.redhat.com/jenkins/job/test-origin-aggregated-logging/1505/):

We are definitely doing some weird tests here -- the `hack/testing/test-curator.sh` is dumping the logs of what it _thinks_ the ops Curator pod is (`logging-curator-ops-1-t17fw`) however we can see there is also the pod `logging-curator-ops-1-60pdg` that the CI infra grabs the logs from at the end of the run -- I am willing to bet the latter pod is the one set up by the Ansible scripts, while the former is set up by the template (???) but in any case @ewolinetz we need to iron this out -- the CI in this repo is not yet simply relying on the Ansible scripts so it's all a mess.

You can see the server create the `logging-curator-ops` deployment from the Ansible setup:

```
I0529 10:06:14.611851    4839 factory.go:108] Adding deployment config "logging-curator-ops"
I0529 10:06:14.622830    4839 rest.go:85] New deployment for "logging-curator-ops" caused by []api.DeploymentCause{api.DeploymentCause{Type:"ConfigChange", ImageTrigger:(*api.DeploymentCauseImageTrigger)(nil)}}
I0529 10:06:14.664604    4839 deployer_controller.go:264] Updated rollout status for "logging/logging-curator-ops-1" from New to Pending (scale: 0)
I0529 10:06:17.681931    4839 deployer_controller.go:264] Updated rollout status for "logging/logging-curator-ops-1" from Pending to Running (scale: 0)
I0529 10:06:18.081971    4839 controller_utils.go:564] Controller logging-curator-ops-1 created pod logging-curator-ops-1-hj6fv
I0529 10:06:20.070194    4839 replication_controller.go:218] Replication controller logging-kibana-ops-1 updated. Desired pod count change: 1->1
I0529 10:06:20.070325    4839 replication_controller.go:554] Finished syncing controller "logging/logging-kibana-ops-1" (91.447µs)
I0529 10:06:20.070580    4839 deployer_controller.go:264] Updated rollout status for "logging/logging-kibana-ops-1" from Running to Complete (scale: 1)
```

Then we can see the RC get messed with twice:

```
I0529 10:20:21.944535    4839 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->0
I0529 10:20:22.101284    4839 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->0
I0529 10:20:22.108068    4839 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->0
I0529 10:21:04.271236    4839 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->1
```

```
I0529 10:25:38.246577    4839 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->0
I0529 10:25:38.266988    4839 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->0
I0529 10:25:38.277244    4839 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->0
I0529 10:26:20.555769    4839 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->1
```

Those last two touches generate the other two pods that this RC had:

```
I0529 10:21:04.296853    4839 controller_utils.go:564] Controller logging-curator-ops-1 created pod logging-curator-ops-1-t17fw
I0529 10:26:20.568444    4839 controller_utils.go:564] Controller logging-curator-ops-1 created pod logging-curator-ops-1-60pdg
```

I can also confirm that just running the `hack/testing/test-curator.sh` script against a normal cluster works fine, so the error is somewhere in `logging.sh` probably.

**Comment by stevekuznetsov** [comment] 2017-05-31 20:23
Hmm... seeing this same failure without the `logging.sh` stuff in the pure-Ansible test [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_logging/5/consoleFull#2899157458b6e51eb7608a5981914356). Seeing the following interactions with the RC:

```
May 31 15:49:12 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->0
May 31 15:49:12 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->0
May 31 15:49:25 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->1
May 31 15:49:25 controller_utils.go:564] Controller logging-curator-ops-1 created pod logging-curator-ops-1-302ph
May 31 15:49:25 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->1
May 31 15:49:25 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->1
May 31 15:49:26 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->1
May 31 15:50:44 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->1
May 31 15:50:46 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->1
May 31 16:02:57 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->0
May 31 16:02:57 controller_utils.go:575] Controller logging-curator-ops-1 deleting pod logging/logging-curator-ops-1-302ph
May 31 16:02:57 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->0
May 31 16:02:57 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->0
May 31 16:03:40 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->1
May 31 16:03:40 controller_utils.go:564] Controller logging-curator-ops-1 created pod logging-curator-ops-1-jzmkn
May 31 16:03:40 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->1
May 31 16:03:40 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->1
May 31 16:03:43 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->1
May 31 16:04:04 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->0
May 31 16:04:04 controller_utils.go:575] Controller logging-curator-ops-1 deleting pod logging/logging-curator-ops-1-jzmkn
May 31 16:04:04 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->0
May 31 16:04:04 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->0
May 31 16:04:46 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 0->1
May 31 16:04:46 controller_utils.go:564] Controller logging-curator-ops-1 created pod logging-curator-ops-1-n1nt3
May 31 16:04:47 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->1
May 31 16:04:47 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->1
May 31 16:04:51 replication_controller.go:218] Replication controller logging-curator-ops-1 updated. Desired pod count change: 1->1
```

**Comment by stevekuznetsov** [comment] 2017-05-31 20:30
In that last test, the logging installation finished at `2017-05-31 15:49:30.837251`. The first date print for the non-ops curator pod was `Wed May 31 19:55:45 UTC 2017` so I'm pretty certain all of the changes are from the `test-curator.sh` script itself.

**Comment by richm** [comment] 2017-05-31 21:02
Not sure, but I think the problem is that the dc/logging-curator-ops has ES_HOST logging-es, which makes this an openshift-ansible/roles/openshift_logging_curator issue

**Comment by richm** [comment] 2017-06-01 00:33
fixed by https://github.com/openshift/openshift-ansible/pull/4341

**Comment by richm** [comment] 2017-06-01 20:50
merged https://github.com/openshift/openshift-ansible/commit/d1e91e82e3cce236ba8fb07ed8c71f6016482562

**Closed by richm** 2017-06-01 20:50 UTC
Labels: kind/bug, priority/P0
