### ISSUE TITLE
aggregated-logging and stacktraces

### ISSUE THREAD

**Issue by miheer** [openshift/origin-aggregated-logging#43] opened 2016-01-13 15:15 UTC
We've installed the aggregated-logging Stack from https://github.com/openshift/origin-aggregated-logging/tree/master/deployment 

Fluentd handels java exception stack traces line per line as a single event. Support requires error messages/stack traces as ONE event, otherwise it is hard to separate different errors recorded at the same time.

**Comment by sosiouxme** [comment] 2016-01-13 15:19
Fluentd would have to know what kind of logs it was looking at in order to know to handle stack traces differently. I'm not sure we can do that generically.

However, it might be reasonable to just assume that any log messages that start with whitespace are to be appended to the previous log line(s) as a single entry.

**Comment by ewolinetz** [comment] 2016-01-13 15:45
I'm a little surprised that these messages would be separate, we are reading our logs in from Docker logs in JSON format so I'd expect that it would include multi-line stack traces.

Can you provide some examples of the logs in question -- both from Kibana and the Container log from /var/log/containers/ ?

**Comment by jcantrill** [comment] 2016-01-14 13:47
@ewolinetz duplicate of #28 ??

**Comment by ewolinetz** [comment] 2016-01-14 13:57
@jcantrill i don't believe so, yet.

**Comment by miheer** [comment] 2016-01-18 14:51
Hi! I have created a bugzilla ticket https://bugzilla.redhat.com/show_bug.cgi?id=1299514 due to privacy reasons and attached the logs there.

**Comment by ewolinetz** [comment] 2016-02-10 16:10
@jcantrill this seems to be a duplicate of #28

**Comment by ewolinetz** [comment] 2016-02-25 20:35
closing to track in #28

**Closed by ewolinetz** 2016-02-25 20:35 UTC
