### ISSUE TITLE
 Access to the ES root url / from a project's pod on Openshift 3.11

### ISSUE THREAD

**Issue by yeplaa** [openshift/origin-aggregated-logging#1641] opened 2019-05-10 14:59 UTC
Hello,

On Openshift 3.9, i use a client pod that connects to the Elasticsearch URL of origin-aggregated-logging.
The client uses his token kubernetes (with his service account) to connect on the url : 

     token=$(oc whoami -t)
     curl -X GET -k -H "X-Proxy-Remote-User: elastalert" -H "Authorization: Bearer ${token}" -i 'https://url'
 
I use this client for watch the logs of project container. 
On the Openshift 3.9, this request is OK.

But with OPenshift 3.11, my client can't connect to the ES root url / . I have the error message following : 
 
      {"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [cluster:monitor/main]     and User [name=system:serviceaccount:dbms-preprod:elastalert, roles=[gen_kibana_b08432e716e206e07b426a7d344ea27b9bc7f96e, gen_user_b08432e716e206e07b426a7d344ea27b9bc7f96e]]"}],"type":"security_exception","reason":"no permissions for [cluster:monitor/main] and User [name=system:serviceaccount:dbms-preprod:elastalert, roles=[gen_kibana_b08432e716e206e07b426a7d344ea27b9bc7f96e, gen_user_b08432e716e206e07b426a7d344ea27b9bc7f96e]]"},

Currently, the access to the root url is mandatory to my client application..

But I can take a GET of my indexes project.dbms-preprod.* : 

    curl -X GET -k -H "X-Proxy-Remote-User: elastalert" -H "Authorization: Bearer ${token}" -i 'https://url/project.dbms-preprod.*'

Is it normal? Has there been any changes regarding the access to the root url with the searchguard and OpenShift ElasticSearch plugins ?  

Thanks for your help

Loïc

**Comment by richm** [comment] 2019-05-10 16:54
> Is it normal?

No, looks like a regression.

> Has there been any changes regarding the access to the root url with the searchguard and OpenShift ElasticSearch plugins ?

Apparently yes.  In 3.11 we moved to use Elasticsearch 5, and in the process, we may have accidentally broken something.

If you can figure out what we broke and how to fix it, patches are welcome.

**Comment by yeplaa** [comment] 2019-05-15 06:48
Thanks @richm for your reply.

Do you reproduce the problem on your side?
I would like to be sure that it is not related to my implementation. 

Have a good day
Loïc

**Comment by scne59** [comment] 2019-05-15 12:37
Same problem here.
A service account that used to access the ES "root" url in 3.10 is now refused in 3.11 for not having "cluster:monitor/main" access.
We managed to workaround that by proxying the connection through an nginx that presents a static version of the JSON as "/" and forwards everything else to the ES backend with proxy_pass.
Elastalert uses "/" to determine the ES version only, which is kind of static. ;-)
There is also a Red Hat Case for this issue: 02382900

**Comment by richm** [comment] 2019-05-15 13:20
What is the expectation here?  That `/` should be readable by any/all accounts?  Are you concerned that this is too open?  If you are concerned, what steps do you think we should take to allow some accounts access to `/` but not other accounts?

**Comment by scne59** [comment] 2019-05-15 14:01
I would assume that if  "/" was readable by any user in 3.10, then it is still ok to have it readable in 3.11 as well.
"/" looks to me a bit like poor man's rootDSE. ;-)
People/applications can use it to make sure they talk to the right cluster, have the right version number etc.. But there is no really "sensitive" information exposed.
And the ES backend is quite well protected behind the oauth-proxy anyway.

**Comment by richm** [comment] 2019-05-15 16:42
ok - I guess the fact that we ever allowed access to `/` was an accident - we don't need it for the strict EFK (and curator) use cases.  So technically it is a regression in behavior from 3.10 to 3.11, but not actually since it was never part of the published and supported "api".

**Comment by yeplaa** [comment] 2019-05-16 12:38
Thanks @scne59 and @richm for your reply.  

@scne59 I have exactly the same problem with my elastalert client.
 Have you seen the configuration responsible for this change?  I did not find in the searchguard configuration.

**Comment by ehvs** [comment] 2019-05-16 13:01
Proactively raised  a BZ [#1710868](https://bugzilla.redhat.com/show_bug.cgi?id=1710868)

**Comment by richm** [comment] 2019-06-21 23:07
fixed by https://github.com/openshift/origin-aggregated-logging/pull/1675

**Closed** 2019-06-26 20:24 UTC
