### ISSUE TITLE
Why we need elasticsearch-cloud-kubernetes plugin?

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/origin-aggregated-logging#986] opened 2018-03-01 13:51 UTC
I want to bring up the question why we need to use [fabric8io/elasticsearch-cloud-kubernetes](https://github.com/fabric8io/elasticsearch-cloud-kubernetes/) plugin while we could probably use DNS and headless services for node discovery in Kubernetes, see older [Jimmi's article](https://jimmidyson.github.io/clustering-on-kubernetes--openshift3-using-dns/) for details.

Is there anything we can not achieve using the DNS and headless services compared to ES Kubernetes plugin approach? Is it security related or does is make K8s probes more complex to implement?

**Comment by lukas-vlcek** [comment] 2018-03-01 13:53
//cc @jimmidyson

**Comment by jcantrill** [comment] 2018-03-01 14:18
Maybe the race condition that @wozniakjan discovered and impl discovery via pod label instead of services?

**Comment by lukas-vlcek** [comment] 2018-03-01 14:55
BTW, I think https://github.com/pires/kubernetes-elasticsearch-cluster uses the same approach for node discovery (ie. pure Kubernetes). Though I did not find any probes implemented in that repo so there might be some challenges how to implemented them eventually (or may be not?).

**Comment by wozniakjan** [comment] 2018-03-05 10:46
The `kubernetes-elasticsearch-cluster` plugin is an implementation of Elasticsearch Zen Discovery API.
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/modules-discovery-zen.html

In order to form Elasticsearch cluster, the nodes need to know how to talk to each other and currently the default way is through a discovery module. The way I understand Zen Discovery, it is a module, an API, as well as an implementation (overloaded terminology maybe?). The default implementation requires `discovery.zen.ping.unicast.hosts: ["node1", "node2", ... , "nodeN"]` in the configuration, where `nodeX` can be a hostname or an IP address. In the kubernetes environment, these are generally not fixed values, pods with Elasticsearch may get killed and respawned with a different IP. Thanks to `kubernetes-elasticsearch-cluster` plugin, we don't have to change configuration in every Elasticsearch pod everytime anything changes.

The mutual-exclusion issue in `kubernetes-elasticsearch-cluster` plugin was rather caused by the convenience the plugin offers with using kubernetes native entities. Not having the plugin would, funnily enough, remove the old issue, but I think it would make it compulsory to change the config with changes in topology.

**Comment by jcantrill** [comment] 2018-07-04 16:03
Closing as we do not.  You may use headless services for which we have switched to in the es5.x branch

**Closed by jcantrill** 2018-07-04 16:03 UTC
Labels: kind/question

**Comment by pavolloffay** [comment] 2018-07-05 07:38
@jcantrill so you don't use the k8s plugin anymore?

**Comment by jcantrill** [comment] 2018-07-05 17:24
@pavolloffay The pending 3.11 release of openshift will not use the referenced plugin. Details regarding the configuration: https://github.com/fabric8io/elasticsearch-cloud-kubernetes#kubernetes-cloud-plugin-for-elasticsearch

**Comment by pavolloffay** [comment] 2018-07-06 07:16
Great to see that! In Jaeger we are also no using it https://github.com/RHsyseng/docker-rhel-elasticsearch
