### ISSUE TITLE
Installation of latest logging stack on OS CP doesn't work: ES wait for YELLOW clusterstate

### ISSUE THREAD

**Issue by boeboe** [openshift/origin-aggregated-logging#789] opened 2017-11-17 14:14 UTC
I am trying to install the logging stack on the latest OpenShift 3.6 Container Platfrom, but this fails due to elastic search deployment failure:

    [me@s2s005co openshift-install]$ oc version
    oc v3.6.173.0.49
    kubernetes v1.6.1+5115d708d7
    features: Basic-Auth GSSAPI Kerberos SPNEGO
    Server https://ocp-api.wccl-lab1.intapp.eu:8443
    openshift v3.6.173.0.21
    kubernetes v1.6.1+5115d708d7

    [me@s2s005co openshift-install]$ oc get pods
    NAME                                       READY     STATUS              RESTARTS   AGE
    logging-curator-1-62wm4                    0/1       CrashLoopBackOff    7          44m
    logging-es-data-master-7gmnohum-4-deploy   1/1       Running             0          24s
    logging-es-data-master-7gmnohum-4-gdwlv    0/1       ContainerCreating   0          13s
    logging-fluentd-0v4nd                      1/1       Running             0          44m
    logging-fluentd-6p75k                      1/1       Running             0          44m
    logging-fluentd-8ct8z                      1/1       Running             0          44m
    logging-fluentd-k8gnj                      1/1       Running             0          44m
    logging-fluentd-r66fl                      1/1       Running             0          44m
    logging-fluentd-zjsln                      1/1       Running             0          44m
    logging-fluentd-zp130                      1/1       Running             0          44m
    logging-kibana-1-mp92p                     2/2       Running             0          44m

    [me@s2s005co openshift-install]$ oc logs logging-es-data-master-7gmnohum-4-gdwlv -f
    [2017-11-17 13:53:09,579][INFO ][container.run            ] Begin Elasticsearch startup script
    [2017-11-17 13:53:09,604][INFO ][container.run            ] Comparing the specified RAM to the maximum recommended for Elasticsearch...
    [2017-11-17 13:53:09,605][INFO ][container.run            ] Inspecting the maximum RAM available...
    [2017-11-17 13:53:09,609][WARN ][container.run            ] Setting the maximum allowable RAM to 1907m which is the largest amount available
    [2017-11-17 13:53:09,610][INFO ][container.run            ] ES_HEAP_SIZE: '953m'
    [2017-11-17 13:53:09,612][INFO ][container.run            ] Setting heap dump location /elasticsearch/persistent/heapdump.hprof
    [2017-11-17 13:53:09,616][INFO ][container.run            ] Checking if Elasticsearch is ready on https://localhost:9200
    [2017-11-17 13:53:21,659][INFO ][container.run            ] Elasticsearch is ready and listening at https://localhost:9200
    [2017-11-17 13:53:21,682][INFO ][container.run            ] Seeding the searchguard ACL index.  Will wait up to 604800 seconds.
    /usr/share/java/elasticsearch/config
    Will connect to localhost:9300 ... done
    2017-11-17 13:53:22 INFO  SearchGuardSSLPlugin:84 - Search Guard 2 plugin not available
    2017-11-17 13:53:22 INFO  SearchGuardPlugin:58 - Clustername: elasticsearch
    2017-11-17 13:53:22 INFO  SearchGuardPlugin:70 - Node [null] is a transportClient: true/tribeNode: false/tribeNodeClient: false
    2017-11-17 13:53:22 INFO  plugins:180 - [Dr. Otto Octavius] modules [], plugins [search-guard-ssl, search-guard2], sites []
    2017-11-17 13:53:23 INFO  DefaultSearchGuardKeyStore:423 - Open SSL not available (this is not an error, we simply fallback to built-in JDK SSL) because                                               of java.lang.ClassNotFoundException: org.apache.tomcat.jni.SSL
    2017-11-17 13:53:23 INFO  DefaultSearchGuardKeyStore:173 - Config directory is /usr/share/java/elasticsearch/config/, from there the key- and truststore                                               files are resolved relatively
    2017-11-17 13:53:23 INFO  DefaultSearchGuardKeyStore:142 - sslTransportClientProvider:JDK with ciphers [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH                                              E_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA                                              _WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH                                              _AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_                                              128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AE                                              S_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_1                                              28_GCM_SHA256]
    2017-11-17 13:53:23 INFO  DefaultSearchGuardKeyStore:144 - sslTransportServerProvider:JDK with ciphers [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH                                              E_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA                                              _WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH                                              _AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_                                              128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AE                                              S_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_1                                              28_GCM_SHA256]
    2017-11-17 13:53:23 INFO  DefaultSearchGuardKeyStore:146 - sslHTTPProvider:null with ciphers []
    2017-11-17 13:53:23 INFO  DefaultSearchGuardKeyStore:148 - sslTransport protocols [TLSv1.2, TLSv1.1]
    2017-11-17 13:53:23 INFO  DefaultSearchGuardKeyStore:149 - sslHTTP protocols [TLSv1.2, TLSv1.1]
    2017-11-17 13:53:23 INFO  transport:99 - [Dr. Otto Octavius] Using [com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] as transport, o                                              verridden by [search-guard-ssl]
    Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
    ERR: Timed out while waiting for a green or yellow cluster state.
       * Try running sgadmin.sh with -icl and -nhnv (If thats works you need to check your clustername as well as hostnames in your SSL certificates)
    0
    [2017-11-17 13:58:25,761][WARN ][container.run            ] Error seeding the searchguard ACL index... retrying in 10 seconds - 0 retries so far
    [2017-11-17 13:58:25,767][WARN ][container.run            ] Seeding will continue to fail until the cluster status is YELLOW
    [2017-11-17 13:58:25,951][INFO ][container.run            ] Remaining red indices: 4
    /usr/share/java/elasticsearch/config
    Will connect to localhost:9300 ... done
    2017-11-17 13:58:36 INFO  SearchGuardSSLPlugin:84 - Search Guard 2 plugin not available
    2017-11-17 13:58:36 INFO  SearchGuardPlugin:58 - Clustername: elasticsearch
    2017-11-17 13:58:36 INFO  SearchGuardPlugin:70 - Node [null] is a transportClient: true/tribeNode: false/tribeNodeClient: false
    2017-11-17 13:58:36 INFO  plugins:180 - [Maynard Tiboldt] modules [], plugins [search-guard-ssl, search-guard2], sites []
    2017-11-17 13:58:36 INFO  DefaultSearchGuardKeyStore:423 - Open SSL not available (this is not an error, we simply fallback to built-in JDK SSL) because of java.lang.ClassNotFoundException: org.apache.tomcat.jni.SSL
    2017-11-17 13:58:36 INFO  DefaultSearchGuardKeyStore:173 - Config directory is /usr/share/java/elasticsearch/config/, from there the key- and truststore files are resolved relatively
    2017-11-17 13:58:36 INFO  DefaultSearchGuardKeyStore:142 - sslTransportClientProvider:JDK with ciphers [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256]
    2017-11-17 13:58:36 INFO  DefaultSearchGuardKeyStore:144 - sslTransportServerProvider:JDK with ciphers [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256]
    2017-11-17 13:58:36 INFO  DefaultSearchGuardKeyStore:146 - sslHTTPProvider:null with ciphers []
    2017-11-17 13:58:36 INFO  DefaultSearchGuardKeyStore:148 - sslTransport protocols [TLSv1.2, TLSv1.1]
    2017-11-17 13:58:36 INFO  DefaultSearchGuardKeyStore:149 - sslHTTP protocols [TLSv1.2, TLSv1.1]
    2017-11-17 13:58:37 INFO  transport:99 - [Maynard Tiboldt] Using [com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] as transport, overridden by [search-guard-ssl]
    Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
    Cannot retrieve cluster state due to: ClusterService was close during health call. This is not an error, will keep on trying ...
       * Try running sgadmin.sh with -icl and -nhnv (If thats works you need to check your clustername as well as hostnames in your SSL certificates)
       * If this is not working, try running sgadmin.sh with --diagnose and see diagnose trace log file)
    [me@s2s005co openshift-install]$

My ansible configuration w.r.t. logging stack is the following:

    openshift_logging_install_logging: true
    openshift_logging_master_public_url: https://ocp-api.wccl-lab1.intapp.eu:8443
    openshift_logging_kibana_hostname: kibana.ocp-apps.wccl-lab1.intapp.eu
    openshift_logging_namespace: logging
    openshift_logging_fluentd_use_journal: true
    openshift_logging_use_mux: false
    openshift_logging_use_ops: false

    openshift_logging_es_ops_allow_cluster_reader: true
    openshift_logging_es_memory_limit: 2G
    openshift_logging_es_pvc_size: 3G
    openshift_logging_elasticsearch_pvc_storage_class_name: heketi

    openshift_logging_kibana_cert: "kibana.ocp-apps.wccl-lab1.intapp.eu.crt"
    openshift_logging_kibana_key: "kibana.ocp-apps.wccl-lab1.intapp.eu.key"
    openshift_logging_kibana_ca: "DigicertBundle.crt"

Logging stack was installed as following:

    ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/openshift-logging.yml

**Comment by boeboe** [comment] 2017-11-17 16:24
UPDATE: seems it has to do with Heketi/GlusterFS as PVC provider. I switched to ephemeral storage, which is working.

**Comment by rahnarsson** [comment] 2017-11-24 11:33
Had a similar issue when upgrading the EFK-stack from 3.5 -> 3.6. The problem is with searchguard indexes that are left red when using persistent storage. 

How to fix:
Inside the Elasticsearch container after the the error above
List problematic indices
`curl --key /etc/elasticsearch/secret/admin-key --cert /etc/elasticsearch/secret/admin-cert --cacert /etc/elasticsearch/secret/admin-ca https://localhost:9200/_cat/indices -s | grep red `

Delete problematic indexes
`curl --key /etc/elasticsearch/secret/admin-key --cert /etc/elasticsearch/secret/admin-cert --cacert /etc/elasticsearch/secret/admin-ca https://localhost:9200/.searchguard.logging-es<some_identifier> -X DELETE

**Comment by jcantrill** [comment] 2018-07-04 18:17
Closing as resolved.  Need to manually work around and should ultimately be resolved with the move to ES5.x and single SG index

**Closed by jcantrill** 2018-07-04 18:17 UTC

**Comment by stewartshea** [comment] 2018-07-27 22:42
Thanks for that post, combined your commands to brute force it with an instance in a very rough state; 

```
for i in $(curl --key /etc/elasticsearch/secret/admin-key --cert /etc/elasticsearch/secret/admin-cert --cacert /etc/elasticsearch/secret/admin-ca https://localhost:9200/_cat/indices -s | grep red | awk '{print $3}'); do curl --key /etc/elasticsearch/secret/admin-key --cert /etc/elasticsearch/secret/admin-cert --cacert /etc/elasticsearch/secret/admin-ca https://localhost:9200/$i -X DELETE; done
```

**Comment by jcantrill** [comment] 2018-07-30 13:36
@stewartshea @rahnarsson Note there are utilities included in the image which will simplify this curl statement:
```
for i in $(oc exec -c elasticsearch $pod -- indices | grep red | awk '{print $3}'); do oc exec -c elasticsearch -c elasticsearch $pod -- es_util --query=$i -X DELETE; done
```
