### ISSUE TITLE
no liveness/readiness probes

### ISSUE THREAD

**Issue by thoraxe** [openshift/origin-aggregated-logging#22] opened 2015-11-13 21:50 UTC
Not sure about readiness, but liveness probes are probably important?

**Comment by sosiouxme** [comment] 2016-05-06 20:52
We can't really have an effective readiness probe on ES as it needs to be considered "ready" in order to be included in the cluster service endpoints so that the cluster can even form. It would take some cleverness to define one for kibana with the auth proxy in front of it, and I'm not sure how much value there is really.

A liveness probe for ES could be valuable. We could exec curl with the admin cert against cluster health endpoint. This could catch weird conditions where the JVM isn't completely dead but also isn't responsive.

**Comment by thoraxe** [comment] 2016-05-06 20:58
What if we had something that changed the probe once the cluster came up "right"?

**Comment by sosiouxme** [comment] 2016-05-06 21:01
Not sure what you mean.

I was hoping there could be some nuance, e.g. a readiness probe per port so
that the cluster membership service might have active endpoints while the
main service does not. However there doesn't really seem to be any concept
like that of the container being "partially" ready.

**Comment by thoraxe** [comment] 2016-05-06 21:04
Well, we have the deployer pod which sets up all the things.

If we could figure out the startup order of things, and when we need to change the probe definition, perhaps the probe itself could call the API and change the probe definition...

I'm just rambling.

**Comment by sosiouxme** [comment] 2016-05-19 15:51
Note https://bugzilla.redhat.com/show_bug.cgi?id=1333666 requests fixing after JVM OOM

**Comment by jcantrill** [comment] 2017-03-30 15:38
Additional possible check in readiness probe:

`
xception in thread "main" java.lang.IllegalStateException: Failed to created node environment
Likely root cause: java.nio.file.AccessDeniedException: /elasticsearch/persistent/logging-es
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:169)
	at org.elasticsearch.node.Node.<init>(Node.java:165)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
`

**Comment by lukas-vlcek** [comment] 2017-04-26 11:44
Just for the record, we added readiness probe for ES
https://github.com/openshift/origin-aggregated-logging/pull/358

**Comment by jcantrill** [comment] 2018-07-04 16:08
Closing as we have discovered liveliness and readiness probe complicates the deployment of Elasticsearch.  The readiness probe has been dumped down from the initial implementation to only ensure the listening port is open.  We prefer for the kublet not to kill a pod.

**Closed by jcantrill** 2018-07-04 16:08 UTC
Labels: kind/enhancement, priority/P0
